# This script install Jenkins on a remote instance
- hosts: all
  tasks: 
    - name: Install Apache at the latest version
      yum: name=httpd state=absent
      become: yes

    - name: Patch up server
      yum: name=* state=latest
      become: yes

    - name: Add Jenkins Red Hat Repository
      yum_repository:
        name: jenkins
        description: Jenkins Repo
        baseurl: http://pkg.jenkins.io/redhat-stable
      become: yes

    - name: Add RPM key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      become: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
      become: yes

    - name: Start up Jenkins
      service: 
        name: jenkins
        state: started
        enabled: yes
      become: yes
