- hosts: localhost

  vars:
    region: ap-southeast-1
    instance_type: t2.micro
    base_image_name: ami-fc5ae39f
    number_of_instances_create: 1

  tasks: 
    - name: Create a suitable set of firewall rules
      ec2_group:
        name: jenkins_server_security_groups
        description: Specific rules for a Jenkins Instance
        region: "{{ region }}"
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
        rules:
          - proto: tcp
            from_port: 22 
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 8080 
            to_port: 8080  
            cidr_ip: 0.0.0.0/0
    
        
    - name: Start up an EC2 Instance
      ec2:
        key_name: my-windows-test
        group: jenkins_server_security_groups
        instance_type: "{{ instance_type }}"
        image: "{{ base_image_name }}"
        wait: yes
        region: "{{ region }}"
        exact_count: "{{ number_of_instances_create }}"
        instance_tags:
          Name: Jenkins_Server
        count_tag:
          Name: Jenkins_Server
      register: ec2

    - name: Gather the new ip addresses
      add_host: groups=new_ec2_instances hostname="{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
        
    - name: Wait for the SSH port to respond
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: new_ec2_instances, tag_Name_Jenkins_Server

  tasks:
    - name: A dummy task to see if dynamic inventory is being found
      debug: msg="Yes, found the inventory"

    - name: Apply Patches
      yum: name=* state=latest
      become: yes

    - name: Add Jenkins Red Hat Repository
      yum_repository:
        name: jenkins
        description: Jenkins Repo
        baseurl: http://pkg.jenkins.io/redhat-stable
      become: yes

    - name: Add RPM key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      become: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
      become: yes

    - name: Start up Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
      become: yes
