# Provision an EC2 instance

- hosts: localhost

  tasks: 
    - name: Start up an EC2 Instance
      ec2:
        key_name: my-windows-test
        group: open-all
        instance_type: t2.micro
        image: ami-fc5ae39f
        wait: yes
        region: ap-southeast-1
        exact_count: 1
        instance_tags:
          Name: Jenkins_Server
        count_tag:
          Name: Jenkins_Server
      register: ec2

    - name: Gather the new ip addresses
      add_host: groups=new_ec2_instances hostname="{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
    
    - name: Debugging
      debug:
        msg: "groups ramon {{groups}}"
        
    - name: Wait for the SSH port to respond
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: new_ec2_instances

  tasks:
    - name: Apply Patches
      yum: name=* state=latest
      become: yes
